# services:
#   app:
#     build:
#       context: ..
#       dockerfile: .devcontainer/Dockerfile

#     volumes:
#       - ../..:/workspaces:cached

#     command: sleep infinity

#   valkey:
#     image: valkey/valkey

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/workspace
    working_dir: /workspace
